ROTATE_DEFAULT = 0
ZOOM_DEFAULT = 0
FLIP_OPTIONS = ['None', 'X', 'Y', 'Both']
BLUR_DEFAULT = 0
CONTRAST_DEFAULT = 0
EFFECT_OPTIONS = ['None', 'Emboss', 'Find edges', 'Contour', 'Edge enhance']
BRIGHTNESS_DEFAULT = 1
VIBRANCE_DEFAULT = 1
GREYSCALE_DEFAULT = False
INVERT_DEFAULT = False

#Colors
WHITE = '#FFF'
GREY = "grey"
BLUE = "#009189"
HOVER = "#006c64"
DARK_GREY = "#4a4a4a"
CLOSE_RED = "#8a0606"
SLIDER_BG = "#64686b"
BACKGROUND = '#242424'
PROGRESS = '#9d9d9d'

DROPDOWN_MAIN_COLOR = '#444'
DROPDOWN_HOVER_COLOR = '#009189'
DROPDOWN_MENU_COLOR = '#666'
